import { ThemeProvider } from '@/src/theme/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import clsx from 'clsx'
import Header from '@/src/features/layout/Header'
import { Footer } from '@/src/features/layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={clsx(inter.className, 'bg-background h-full')}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <div className='flex flex-col h-full'>
            <div className='flex-1 max-w-lg m-auto py-12 w-full'>
              <Header />
            {children}
            <Footer />
            </div>
          </div>
        </ThemeProvider>
        </body>
    </html>
  )
}
